// ============================================================
//  VANGUARD MD — commands/arena.js
//  Arena of Valor Style Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '📝 *Arena Text Effect*\n\n' +
      'Usage:\n' +
      '.arena Your Text Here\n\n' +
      'Example: .arena Hakimi'
    )
  }

  await reply('⏳ Generating Arena of Valor style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/create-cover-arena-of-valor-by-mastering-360.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `Arena of Valor Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Arena command error:', error)
    await reply('❌ Error generating Arena effect: ' + error.message)
  }
}