// ============================================================
//  VANGUARD MD — commands/blackpink.js
//  Blackpink Style Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '📝 *Blackpink Text Effect*\n\n' +
      'Usage:\n' +
      '.blackpink Your Text Here\n\n' +
      'Example: .blackpink Hakimi'
    )
  }

  await reply('⏳ Generating Blackpink style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/create-a-blackpink-style-logo-with-members-signatures-810.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `Blackpink Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Blackpink command error:', error)
    await reply('❌ Error generating Blackpink effect: ' + error.message)
  }
}