// ============================================================
//  VANGUARD MD — commands/devil.js
//  Devil Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '🎨 *Devil Text Effect*\n\n' +
      'Usage:\n' +
      '.devil Your Text Here\n\n' +
      'Example: .devil Hakimi'
    )
  }

  await reply('⏳ Generating Devil style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/neon-devil-wings-text-effect-online-683.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `😈 Devil Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Devil command error:', error)
    await reply('❌ Error generating Devil effect: ' + error.message)
  }
}