// ============================================================
//  VANGUARD MD — commands/fire.js
//  Fire / Flame Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '🔥 *Fire Text Effect*\n\n' +
      'Usage:\n' +
      '.fire Your Text Here\n\n' +
      'Example: .fire Hakimi'
    )
  }

  await reply('⏳ Generating Fire / Flame style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/flame-lettering-effect-372.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `🔥 Fire / Flame Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Fire command error:', error)
    await reply('❌ Error generating Fire effect: ' + error.message)
  }
}