// ============================================================
//  VANGUARD MD — commands/glitch.js
//  Glitch Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '⚡ *Glitch Text Effect*\n\n' +
      'Usage:\n' +
      '.glitch Your Text Here\n\n' +
      'Example: .glitch Hakimi'
    )
  }

  await reply('⏳ Generating Glitch style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `⚡ Glitch Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Glitch command error:', error)
    await reply('❌ Error generating Glitch effect: ' + error.message)
  }
}