// ============================================================
//  VANGUARD MD — commands/hacker.js
//  Hacker / Anonymous Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '💻 *Hacker Text Effect*\n\n' +
      'Usage:\n' +
      '.hacker Your Text Here\n\n' +
      'Example: .hacker Hakimi'
    )
  }

  await reply('⏳ Generating Hacker style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/create-anonymous-hacker-avatars-cyan-neon-677.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `💻 Hacker / Anonymous Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Hacker command error:', error)
    await reply('❌ Error generating Hacker effect: ' + error.message)
  }
}