// ============================================================
//  VANGUARD MD — commands/ice.js
//  Ice Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '❄️ *Ice Text Effect*\n\n' +
      'Usage:\n' +
      '.ice Your Text Here\n\n' +
      'Example: .ice Hakimi'
    )
  }

  await reply('⏳ Generating Ice style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/ice-text-effect-online-101.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `❄️ Ice Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Ice command error:', error)
    await reply('❌ Error generating Ice effect: ' + error.message)
  }
}