// ============================================================
//  VANGUARD MD — commands/impressive.js
//  Impressive / 3D Colorful Paint Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '✨ *Impressive Text Effect*\n\n' +
      'Usage:\n' +
      '.impressive Your Text Here\n\n' +
      'Example: .impressive Hakimi'
    )
  }

  await reply('⏳ Generating Impressive style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/create-3d-colorful-paint-text-effect-online-801.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `✨ Impressive Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Impressive command error:', error)
    await reply('❌ Error generating Impressive effect: ' + error.message)
  }
}