// ============================================================
//  VANGUARD MD — commands/leaves.js
//  Leaves / Green Brush Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '🍃 *Leaves Text Effect*\n\n' +
      'Usage:\n' +
      '.leaves Your Text Here\n\n' +
      'Example: .leaves Hakimi'
    )
  }

  await reply('⏳ Generating Leaves style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/green-brush-text-effect-typography-maker-online-153.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `🍃 Leaves Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Leaves command error:', error)
    await reply('❌ Error generating Leaves effect: ' + error.message)
  }
}