// ============================================================
//  VANGUARD MD — commands/light.js
//  Light / Futuristic Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '💡 *Light Text Effect*\n\n' +
      'Usage:\n' +
      '.light Your Text Here\n\n' +
      'Example: .light Hakimi'
    )
  }

  await reply('⏳ Generating Light / Futuristic style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/light-text-effect-futuristic-technology-style-648.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `💡 Light / Futuristic Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Light command error:', error)
    await reply('❌ Error generating Light effect: ' + error.message)
  }
}