// ============================================================
//  VANGUARD MD — commands/matrix.js
//  Matrix Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '🌿 *Matrix Text Effect*\n\n' +
      'Usage:\n' +
      '.matrix Your Text Here\n\n' +
      'Example: .matrix Hakimi'
    )
  }

  await reply('⏳ Generating Matrix style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/matrix-text-effect-154.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `🌿 Matrix Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Matrix command error:', error)
    await reply('❌ Error generating Matrix effect: ' + error.message)
  }
}