// ============================================================
//  VANGUARD MD — commands/metallic.js
//  Metallic Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '🛠️ *Metallic Text Effect*\n\n' +
      'Usage:\n' +
      '.metallic Your Text Here\n\n' +
      'Example: .metallic Hakimi'
    )
  }

  await reply('⏳ Generating Metallic style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/impressive-decorative-3d-metal-text-effect-798.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `🛠️ Metallic Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Metallic command error:', error)
    await reply('❌ Error generating Metallic effect: ' + error.message)
  }
}