// ============================================================
//  VANGUARD MD — commands/neon.js
//  Neon Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '🌟 *Neon Text Effect*\n\n' +
      'Usage:\n' +
      '.neon Your Text Here\n\n' +
      'Example: .neon Hakimi'
    )
  }

  await reply('⏳ Generating Neon style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/create-colorful-neon-light-text-effects-online-797.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `🌟 Neon Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Neon command error:', error)
    await reply('❌ Error generating Neon effect: ' + error.message)
  }
}