// ============================================================
//  VANGUARD MD — commands/purple.js
//  Purple Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '💜 *Purple Text Effect*\n\n' +
      'Usage:\n' +
      '.purple Your Text Here\n\n' +
      'Example: .purple Hakimi'
    )
  }

  await reply('⏳ Generating Purple style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/purple-text-effect-online-100.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `💜 Purple Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Purple command error:', error)
    await reply('❌ Error generating Purple effect: ' + error.message)
  }
}