// ============================================================
//  VANGUARD MD — commands/sand.js
//  Sand Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '🏖️ *Sand Text Effect*\n\n' +
      'Usage:\n' +
      '.sand Your Text Here\n\n' +
      'Example: .sand Hakimi'
    )
  }

  await reply('⏳ Generating Sand style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/write-names-and-messages-on-the-sand-online-582.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `🏖️ Sand Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Sand command error:', error)
    await reply('❌ Error generating Sand effect: ' + error.message)
  }
}