// ============================================================
//  VANGUARD MD — commands/snow.js
//  Snow / 3D Snow Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '❄️ *Snow Text Effect*\n\n' +
      'Usage:\n' +
      '.snow Your Text Here\n\n' +
      'Example: .snow Hakimi'
    )
  }

  await reply('⏳ Generating Snow style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/create-a-snow-3d-text-effect-free-online-621.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `❄️ Snow Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Snow command error:', error)
    await reply('❌ Error generating Snow effect: ' + error.message)
  }
}