// ============================================================
//  VANGUARD MD — commands/thunder.js
//  Thunder Text Effect (Open to everyone)
// ============================================================

const mumaker = require('mumaker')

module.exports = async (ctx) => {
  const { reply, sock, args, msg } = ctx

  const text = args.join(' ').trim()

  if (!text) {
    return reply(
      '⚡ *Thunder Text Effect*\n\n' +
      'Usage:\n' +
      '.thunder Your Text Here\n\n' +
      'Example: .thunder Hakimi'
    )
  }

  await reply('⏳ Generating Thunder style text effect...')

  try {
    const result = await mumaker.ephoto(
      'https://en.ephoto360.com/thunder-text-effect-online-97.html', 
      text
    )

    if (!result || !result.image) {
      return reply('❌ Failed to generate image. Please try again.')
    }

    await sock.sendMessage(msg.key.remoteJid, {
      image: { url: result.image },
      caption: `⚡ Thunder Style Effect\n\nGenerated by VANGUARD MD`,
    }, { quoted: msg })

  } catch (error) {
    console.error('Thunder command error:', error)
    await reply('❌ Error generating Thunder effect: ' + error.message)
  }
}